# cluster configuration
fastqc:
  Job_name: Fastqc # -J
  Mem: 5000 # --mem
  Cores: 1 #-c
  Partition: cpu_short # -p
  Time: 240 # -t
  Error: logs/slurm_reports/slurm-%j.out # -e

fastqc_post_trim:
  Job_name: Fastqc_post_trim # -J
  Mem: 10000 # --mem
  Cores: 1 #-c
  Partition: cpu_short # -p
  Time: 240 # -t
  Error: logs/slurm_reports/slurm-%j.out # -e

trim:
  Job_name: trim # -J
  Mem: 5000 # --mem
  Partition: cpu_short # -p
  Cores: 4 #-c
  Time: 240 # -t
  Error: logs/slurm_reports/slurm-%j.out # -e

align:
  Job_name: align # -J
  Mem: 60000 # --mem
  Partition: cpu_short # -p
  Cores: 10 #-c
  Time: 240 # -t
  Error: logs/slurm_reports/slurm-%j.out # -e

count:
  Job_name: count # -J
  Mem: 30000 # --mem
  Partition: cpu_short # -p
  Cores: 20 #-c
  Time: 60 # -t
  Error: logs/slurm_reports/slurm-%j.out # -e